// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/battle-pass-fx/Arcane.tsx": () => import("../components/mockups/battle-pass-fx/Arcane.tsx"),
  "./components/mockups/battle-pass-fx/Cosmic.tsx": () => import("../components/mockups/battle-pass-fx/Cosmic.tsx"),
  "./components/mockups/battle-pass-fx/Forge.tsx": () => import("../components/mockups/battle-pass-fx/Forge.tsx"),
  "./components/mockups/palettes/ColorPalettes.tsx": () => import("../components/mockups/palettes/ColorPalettes.tsx")
};
